---

- ansible.builtin.include_tasks: fetch-secret.yml

- name: Set Variables
  set_fact:
    auth_username: "{{keycloak_secret.resources[0].data.username|b64decode}}"
    auth_password: "{{keycloak_secret.resources[0].data.password|b64decode}}"
  when: auth_secret.name is defined

- name: Create or update Keycloak realm
  community.general.keycloak_realm:
    auth_client_id: "{{auth_client_id}}"
    auth_keycloak_url: "{{auth_keycloak_url}}"
    auth_realm: "{{auth_realm}}"
    auth_username: "{{auth_username}}"
    auth_password: "{{auth_password}}"
    id: "{{realm}}"
    realm: "{{realm}}"
    state: "{{state}}"
    validate_certs: "{{validate_certs | default('true')}}"