# permissions for end users to edit clients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: client-editor-role
rules:
- apiGroups:
  - admin.keycloak.org
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admin.keycloak.org
  resources:
  - clients/status
  verbs:
  - get
