# permissions for end users to edit realms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: realm-editor-role
rules:
- apiGroups:
  - admin.keycloak.org
  resources:
  - realms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admin.keycloak.org
  resources:
  - realms/status
  verbs:
  - get
