---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for admin.keycloak.org/v1alpha1, Kind: Realm
  ##
  - apiGroups:
      - admin.keycloak.org
    resources:
      - realms
      - realms/status
      - realms/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for admin.keycloak.org/v1alpha1, Kind: Client
  ##
  - apiGroups:
      - admin.keycloak.org
    resources:
      - clients
      - clients/status
      - clients/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for admin.keycloak.org/v1alpha1, Kind: User
  ##
  - apiGroups:
      - admin.keycloak.org
    resources:
      - users
      - users/status
      - users/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
