apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
          {
            "apiVersion": "admin.keycloak.org/v1alpha1",
            "kind": "Realm",
            "metadata": {
                "name": "realm-sample",
                "namespace": "default",
            },
            "spec": {
                "auth_client_id": "admin-cli",
                "auth_keycloak_url": "https://example-kc-service.default.svc:8443",
                "auth_realm": "master",
                "auth_secret": {
                    "name": "example-kc-initial-admin",
                    "namespace": "default"
                },
                "realm": "demo"
            }
            
        }
      ]
    capabilities: Basic Install
  name: keycloak-admin-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    # a list of CRDs that this operator owns
    # name is the metadata.name of the CRD (which is of the form <plural>.<group>)
    - name: realms.admin.keycloak.org
      # version is the spec.versions[].name value defined in the CRD
      version: v1alpha1
      # kind is the CamelCased singular value defined in spec.names.kind of the CRD.
      kind: Realm

  description: Keycloak Operator to create and manage admin resources such as Realms, Users, Clients etc.
  displayName: keycloak-admin-operator
  maintainers:
  - email: drpdishant@gmail.com
    name: Dishant Pandya
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keycloak
  - admin
  links:
  - name: Keycloak Admin Operator
    url: https://github.com/drpdishant/keycloak-admin-operator.git
  maturity: alpha
  provider:
    name: Keycloak
    url: keycloak.org
  version: 0.0.1
  